# Generated by Django 5.1.4 on 2025-01-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0002_remove_servico_categoria_remove_servico_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='tipo_corte',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico'),
        ),
    ]
