# Generated by Django 5.1.4 on 2025-01-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('corte', 'Corte de cabelo'), ('barba', 'Barba'), ('outro', 'Outros serviços')], max_length=50)),
            ],
        ),
    ]
