# Generated by Django 5.1.4 on 2025-01-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_servico_categoria_remove_servico_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
