# Generated by Django 5.1.4 on 2025-01-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
    ]
